=== eurostat/EU-SILC/XML_CONFIG/XSD/LVAL.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- W3C Schema generated by XMLSpy v2018 rel. 2 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="check">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="loop" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="title" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="subtype" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="selresp" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="select" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="from" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="join" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="on" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="join2" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="on2" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="join3" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="on3" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="join4" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="on4" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="where" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="group" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="having" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:integer"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="start" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:integer"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="end" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:integer"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="category" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="cross-sectional"/>
						<xs:enumeration value="longitudinal"/>
						<xs:enumeration value="evolution"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="module" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="adhoc"/>
						<xs:enumeration value="recur3"/>
						<xs:enumeration value="recur6"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="from">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="D"/>
				<xs:enumeration value="R"/>
				<xs:enumeration value="H"/>
				<xs:enumeration value="P"/>
				<xs:enumeration value="d"/>
				<xs:enumeration value="r"/>
				<xs:enumeration value="h"/>
				<xs:enumeration value="p"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="group">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="having">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="join">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="D"/>
				<xs:enumeration value="R"/>
				<xs:enumeration value="H"/>
				<xs:enumeration value="P"/>
				<xs:enumeration value="d"/>
				<xs:enumeration value="r"/>
				<xs:enumeration value="h"/>
				<xs:enumeration value="p"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="join2">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="D"/>
				<xs:enumeration value="R"/>
				<xs:enumeration value="H"/>
				<xs:enumeration value="P"/>
				<xs:enumeration value="d"/>
				<xs:enumeration value="r"/>
				<xs:enumeration value="h"/>
				<xs:enumeration value="p"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="join3">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="D"/>
				<xs:enumeration value="R"/>
				<xs:enumeration value="H"/>
				<xs:enumeration value="P"/>
				<xs:enumeration value="d"/>
				<xs:enumeration value="r"/>
				<xs:enumeration value="h"/>
				<xs:enumeration value="p"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="join4">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="D"/>
				<xs:enumeration value="R"/>
				<xs:enumeration value="H"/>
				<xs:enumeration value="P"/>
				<xs:enumeration value="d"/>
				<xs:enumeration value="r"/>
				<xs:enumeration value="h"/>
				<xs:enumeration value="p"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="LVAL">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="preprocessing" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="check" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="globalID">
			<xs:selector xpath="check"/>
			<xs:field xpath="@id"/>
		</xs:unique>
	</xs:element>
	<xs:element name="on">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="on2">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="on3">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="on4">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="select">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="subtype">
		<xs:complexType/>
	</xs:element>
	<xs:element name="selresp">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Y"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="title">
		<xs:simpleType>
			<xs:restriction base="xs:anyURI"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="where" type="xs:string"/>
	<xs:element name="loop">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="x" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="x">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="[D,R,H,P]{1}[0-z]+"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="step">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="preprocessing">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="step" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== eurostat/EU-SILC/XML_CONFIG/XML/LVAL/LVAL-R-2026.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2020 rel. 2 sp1 (x64) (http://www.altova.com) by  (European Commission - DG EUROSTAT) -->
<!-- Revision:  December 9th 2022 -->
<LVAL xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../XSD/LVAL.xsd">

  <preprocessing>
    <step>HH_AGE_0_15</step>
    <step>HH_RL020</step>
    <step>RL010_060_SUM</step>
    <step>PAR_CHI_AGE_DIFF</step>
  </preprocessing>
  
<!-- WEIGHTS -->
  <check id="001">
    <title>Weights - Error: DB090 - Household (DB090) vs Personal (RB050) cross-sectional weight mismatch</title>
    <select>a.DB010,a.DB030,a.DB090,b.RB050</select>
    <from>d</from>
    <join>r</join>
    <on>DB030 = RB040 and DB010 = RB010</on>
    <where>(DB090 GE 0) AND (RB050 GE 0) AND (ABS(DB090 - RB050) GT 0.01*DB090)</where>
  </check>
  
<!--Non respondents-->
<check id="002">
<title>Weight - Error: DB090 - Cross sectional weight must be 0 for non-respondents (DB135 ne 1)</title>
<select>DB010, DB030, DB135, DB090 </select>
<from>d</from>
<where>DB135 ne 1 and DB090 ne 0 and DB010=$year</where>
</check>
<check id="003">
<title>Weight - Error: DB095 - longitudinal weight must be 0 for non-respondents (DB135 ne 1)</title>
<select>DB010, DB030, DB076, DB135, DB095 </select>
<from>d</from>
<where>DB135 ne 1 and DB076 GT 1 and DB095 NE 0 and DB010=$year</where>
</check>
<!--Cross-sectional weights: -->
<check id="004">
<title>Weight - Error: DB090 - Cross sectional weight must be filled and positive for respondents of current year</title>
<select>DB010, DB030, DB135, DB090 </select>
<from>d</from>
<where>DB135 = 1 and DB010=$YEAR and (DB090 LT 0 or DB090 = .) </where>
</check>
<check id="005">
<title>Weight - Error: DB090 - Cross sectional weight must be missing with flag = -7 for previous years</title>
<select>DB010, DB030, DB090, DB090_F </select>
<from>d</from>
<where>DB010 LT $YEAR and (DB090 NE . or DB090_F NE -7) </where>
</check>
<check id="006">
<title>Weight - Error: RB050 - Cross sectional weight must be filled and positive for current year</title>
<select>RB010, RB030, RB110, RB050, RB050_F </select>
<from>r</from>
<where>RB010=$YEAR and RB110 LT 5 and RB110 GT 0 and (RB050 LT 0 or RB050 = .) </where>
</check>
<check id="007">
<title>Weight Error - RB050 - Cross sectional weight must be missing with flag = -7 for previous years</title>
<select>RB010, RB030, RB110, RB050, RB050_F </select>
<from>r</from>
<where>RB010 LT $YEAR and RB110 LT 5 and RB110 GT 0 and (RB050 NE . or RB050_F NE -7)</where>
</check>
<check id="008">
<title>Weight - Error - PB040 - Cross sectional weight must be filled and positive for current year</title>
<select>PB010, PB030, PB040 </select>
<from>p</from>
<where>PB010=$YEAR and (PB040 LT 0 or PB040 = .) </where>
</check>
<check id="009">
<title>Weight - Error: PB040 - Cross sectional weight must be missing with flag = -7 for previous years</title>
<select>PB010, PB030, PB040, PB040_F </select>
<from>p</from>
<where>PB010 LT $YEAR and (PB040 NE . or PB040_F NE -7)</where>
</check>
<!--Longitudinal>weights: -->
<check id="010">
<title>Weight - Error: DB095 - Longitudinal weight must be filled and positive for every respondent but in new wave of current year</title>
<select>DB010, DB030, DB135, DB076, DB095 </select>
<from>d</from>
<where>DB135 = 1 and ((DB010=$YEAR and DB076 ne 1) or DB010 LT $YEAR) and (DB095 LT 0 or DB095 = .) </where>
</check>
<check id="011">
<title>Weight - Error: DB095 - Longitudinal weight must be missing for new wave of current year</title>
<select>DB010, DB030, DB135, DB076, DB095 </select>
<from>d</from>
<where>DB135 = 1 and DB010=$YEAR and DB076 = 1 and DB095 NE .</where>
</check>
<check id="012">
<title>Weight - Error: RB062 - Longitudinal weight (2 years duration) must be filled and positive for current year and waves greater than 1</title>
<select>RB010, RB030, RB110, DB076, RB062, RB062_F </select>
<from>r</from>
<join>d</join>
<on>RB010=DB010 and RB020=DB020 and RB040=DB030</on>
<where>RB010=$YEAR and RB110 LT 5 and RB110 GT 0 and DB076 GT 1 and (RB062 LT 0 or RB062 = .) and RB062_F ne -1</where>
</check>
<check id="013">
<title>Weight - Error: RB062 - Longitudinal weight (2 years duration) must be missing with flag = -2 for previous years or waves lower than 2</title>
<select>RB010, RB030, RB110, DB076, RB062, RB062_F </select>
<from>r</from>
<join>d</join>
<on>RB010=DB010 and RB020=DB020 and RB040=DB030</on>
<where>((RB010=$YEAR and DB076 LT 2 and DB076 GT 0) or RB010 LT $YEAR) and RB110 LT 5 and (RB062 NE . or RB062_F NE -2)</where>
</check>
<check id="014">
<title>Weight - Error: RB063 - Longitudinal weight (3 years duration) must be filled and positive for current year and waves greater than 2</title>
<select>RB010, RB030, RB110, DB076, RB063, RB063_F  </select>
<from>r</from>
<join>d</join>
<on>RB010=DB010 and RB020=DB020 and RB040=DB030</on>
<where>RB010=$YEAR and RB110 LT 5 and RB110 GT 0 and DB076 GT 2 and (RB063 LT 0 or RB063 = .) and RB063_F ne -1</where>
</check>
<check id="015">
<title>Weight - Error: RB063 - Longitudinal weight (3 years duration) must be missing with flag = -2 for previous years or waves lower than 3</title>
<select>RB010, RB030, RB110, DB076, RB063, RB063_F </select>
<from>r</from>
<join>d</join>
<on>RB010=DB010 and RB020=DB020 and RB040=DB030</on>
<where>((RB010=$YEAR and DB076 LT 3 and DB076 GT 0) or RB010 LT $YEAR) and RB110 LT 5 and RB110 GT 0 and (RB063 NE . or RB063_F NE -2)</where>
</check>
<check id="016">
<title>Weight - Error: RB064 - Longitudinal weight (4 years duration) must be filled and positive for current year and waves greater than 3</title>
<select>RB010, RB030, RB110, DB076, RB064, RB064_F </select>
<from>r</from>
<join>d</join>
<on>RB010=DB010 and RB020=DB020 and RB040=DB030</on>
<where>RB010=$YEAR and RB110 LT 5 and RB110 GT 0 and DB076 GT 3 and (RB064 LT 0 or RB064 = .) and RB064_F ne -1</where>
</check>
<check id="017">
<title>Weight - Error: RB064 - Longitudinal weight (4 years duration) must be missing with flag = -2 for previous years or waves lower than 4</title>
<select>RB010, RB030, RB110, DB076, RB064, RB064_F </select>
<from>r</from>
<join>d</join>
<on>RB010=DB010 and RB020=DB020 and RB040=DB030</on>
<where>((RB010=$YEAR and DB076 LT 4 and DB076 GT 0) or RB010 LT $YEAR) and RB110 LT 5 and RB110 GT 0 and (RB064 NE . or RB064_F NE -2)</where>
</check>
<check id="018">
<title>Weight - Error: RB065 - Longitudinal weight (5 years duration) must be filled and positive for current year and waves greater than 4</title>
<select>RB010, RB030, RB110, DB076, RB065, RB065_F </select>
<from>r</from>
<join>d</join>
<on>RB010=DB010 and RB020=DB020 and RB040=DB030</on>
<where>RB010=$YEAR and RB110 LT 5 and RB110 GT 0 and DB076 GT 4 and (RB065 LT 0 or RB065 = .) and RB065_F ne -1</where>
</check>
<check id="019">
<title>Weight - Error: RB065 - Longitudinal weight (5 years duration) must be missing with flag = -2 for previous years or waves lower than 5</title>
<select>RB010, RB030, RB110, DB076, RB065, RB065_F </select>
<from>r</from>
<join>d</join>
<on>RB010=DB010 and RB020=DB020 and RB040=DB030</on>
<where>((RB010=$YEAR and DB076 LT 5 and DB076 GT 0) or (RB010 LT $YEAR and RB010 GT 2020)) and RB110 LT 5 and RB110 GT 0 and (RB065 NE . or RB065_F NE -2) and RB020 in ("BE", "BG", "IT", "IE", "NL", "SE", "YY")</where>
</check>
<check id="020">
<title>Weight - Error -RB066 - Longitudinal weight (6 years duration) must be filled and positive for current year and waves greater than 5</title>
<select>RB010, RB030, RB110, DB076, RB066, RB066_F </select>
<from>r</from>
<join>d</join>
<on>RB010=DB010 and RB020=DB020 and RB040=DB030</on>
<where>RB010=$YEAR and RB110 LT 5 and RB110 GT 0 and DB076 GT 5 and (RB066 LT 0 or RB066 = .) and RB066_F ne -1</where>
</check>
<check id="021">
<title>Weight - Error: RB066 - Longitudinal weight (6 years duration) must be missing with flag = -2 for previous years or waves lower than 6</title>
<select>RB010, RB030, RB110, DB076, RB066, RB066_F </select>
<from>r</from>
<join>d</join>
<on>RB010=DB010 and RB020=DB020 and RB040=DB030 </on>
<where>((RB010=$YEAR and DB076 LT 6 and DB076 GT 0) or (RB010 LT $YEAR and RB010 GT 2020)) and RB110 LT 5 and RB110 GT 0 and (RB066 NE . or RB066_F NE -2) and RB020 in ("BE", "BG", "IT", "IE", "NL", "SE", "YY")</where>
</check>
<check id="022">
<title>Weight - Error: RB065 - Longitudinal weight (5 years duration) must be missing and flag=-5 for current year</title>
<select>RB010, RB030, RB110, RB065, RB065_F</select>
<from>r</from>
<where>RB010=$YEAR and RB020 not in ("BE", "BG", "IT", "IE", "NL", "SE", "YY") and RB110 LT 5 and RB110 GT 0 and (RB065 ne . or RB065_F ne -5)</where>
</check>
<check id="023">
<title>Weight - Error: RB066 - Longitudinal weight (6 years duration) must be missing and flag=-5 for current year</title>
<select>RB010, RB030, RB110, RB066, RB066_F</select>
<from>r </from>
<where>RB010=$YEAR and RB020 not in ("BE", "BG", "IT", "IE", "NL", "SE", "YY") and RB110 LT 5 and RB110 GT 0 and (RB066 ne . or RB066_F ne -5)</where>
</check>
<!--selected respondents weights:-->
<check id="024">
<title>Weight - Error: PB060 - selected respondent cross sectional weight must be filled and positive for selected respondents in current year</title>
<select>PB010, PB030, SELRES, PB060 </select>
<from>p</from>
<where>PB010=$YEAR and SELRES=2 and (PB060 LT 0 or PB060 = .) </where>
</check>
<check id="025">
<title>Weight - Error: PB060 - selected respondent cross sectional weight must be missing with flag = -7 for previous years</title>
<select>PB010, PB030, SELRES, PB060, PB060_F</select>
<from>p</from>
<where>PB010 LT $YEAR and (SELRES=2 or SELRES=3) and (PB060 NE . or PB060_F NE -7)</where>
</check>
<check id="026">
